# holds solutions to the test questions / parameters
# called by the test_keep_to_calc.py file

single_workout1_solution = ['22 November, day 3; ',
                            'Bench press 75kg: 8,8,7,6,8; ',
                            'Db incline 24ea: 8,9,9; ',
                            'Ohp 40kg: 8,8,7; ',
                            'Assisted pull up -9kg: 7,5, -18kg: 7,5; ',
                            'Chest supported row 59kg: 9, 45kg: 12,12; ',
                            'Machine lateral raise 45kg: 15,18; ',
                            'Close grip bench press 60kg: 12,8,8,7; ',
                            'Bayesian curl 23kg: 10, 18kg: 12,12; ',
                            'RC rotations; ',
                            'Dead hang 1. ',
                            'Est 65 mins']

single_workout2_solution = ['21 November, day 2; ',
                            'Squat 90kg: 8,8,8; ',
                            'Deadlift 90kg: 7,7; ',
                            'Barbell momentum shrug and hold (3s top, 5s bottom) 130kg: 5,5; ',
                            'Pendlay row 70kg: 8,8,8; ',
                            'Calf press machine 79kg: 16,17; ',
                            'Leg raise: 10,10, 5kg: 10; ',
                            'Machine crunch 30kg: 10,20; ',
                            'Bayesian curl 40lb: 10, 32lb: 7, 22lb: 12; ',
                            'Back supported Tricep pushdown 23kg: 15,18; ',
                            'Machine lateral raise 45kg: 17,17; ',
                            'Dead hang 1. ',
                            'Est ?? mins']

single_workout3_solution = ['24 November, day 4; ',
                            'Squat 100kg: 7,7,7,7,7; ',
                            'Rack pull 110kg (with hold 2:5): 5,5,5; ',
                            'Pendlay rows 70kg: 8,8,8,8; ',
                            'Face pulls 130lb: 15,15,15; ',
                            'Calf press machine 79kg: 15,20; ',
                            '(Kinda low) Hanging circular leg raise (no reset): 9,6; ',
                            'Hanging circular leg raise with reset: 8,6; ',
                            'Machine crunch 36kg with reset: 12, without reset 36kg: 8; ',
                            'Bayesian curl 10.2kg: 11,12; ',
                            'Machine lateral raise 41kg: 20,20; ',
                            'Dead hang. ',
                            'Est 91 mins']

# because our program only extracts one workout at time, we only want the first workout returned
multiple_workout1_solution = single_workout1_solution

# solution to a "noisy" dataset, where there's junk in the file unrelated to workouts
# we expect the program to ignore junk, and return only workout data
noisy_data_single_workout1_solution = single_workout1_solution

multiple_workout2_solution = ['5 October; ',
                              'Flat leg press 107kg: 10,10,10; ',
                              'Romanian deadlift 100kg: 6, 110kg: 5,6; ',
                              'Wide grip power shrug 125kg: 12; ',
                              'Hanging toes to bar: 6,6,6; ',
                              'Calf press machine 97.5kg: 12,12; ',
                              'Bicycle cable crunch 37kg: 15; ',
                              'Cable crunch 42kg: 15; ',
                              'Dumbbell lateral raise 9ea: 15,10; ',
                              'Machine rear delt fly 52kg: 12,12; ',
                              'Light face pulls; ',
                              'Og curl 14ea: 12; ',
                              'Hammer curl 14ea: 12; ',
                              'EZ bar momentum modified skullcrusher 10ea: 14,13; ',
                              'Neck forwards curl, 15kg on forehead: 15,15; ',
                              'Dead hang. ',
                              'Est 69 mins']

multiple_workout3_solution_matrix = [['24 October',
                                      '',
                                      'Flat leg press 107kg: 10,10,10',
                                      '/Box squat? Low bar?',
                                      '',
                                      '/+ Leg press, loaded with 160kg: 10,10,',
                                      '(10,10,10)',
                                      "/ROM feels insufficient but I can't safely extend it",
                                      '/Left knee faint twinge even at very top of movement when starting to '
                                      'push',
                                      "/Don't even consider hack squat - it feels so unnatural in this gym",
                                      '',
                                      '',
                                      'Deadlift 120kg: 6, 130kg: 6, 135kg: 6',
                                      '(120kg: 6, 130kg: 6,6)',
                                      '/Keep focus on back.',
                                      '/Dead stop! Straighter neck!',
                                      '/The 3 staggered sets up to 130kg is too much for working on form',
                                      '/High RPE is particularly draining',
                                      '/Thumb slipped a little on the last set! Care',
                                      '',
                                      '/+ Romanian deadlift 100kg: 6, 110kg: 5,6',
                                      "/Like stiff legged but bar doesn't touch ground between reps",
                                      '/Form needs work',
                                      '/Legs should be basically locked',
                                      '',
                                      '',
                                      '/+ Wide grip power shrug 125kg: 12',
                                      '(120kg: 12)',
                                      '',
                                      '+ Cable machine wide grip shrugs, 2 sets',
                                      '/Close machine 42kg with Widest handles in the gym',
                                      '/Strict form',
                                      '',
                                      '',
                                      'Hanging toes to bar: 6,6,6',
                                      '(8,8 / 6,6,8 no L sits)',
                                      '/Replace wipers with these. Active shoulders',
                                      '/Added extra work in place of shrugs',
                                      '/RPE ?',
                                      '',
                                      '',
                                      'Calf press machine 97.5kg: 12,12',
                                      '(88kg: 15,15 / 97.5kg: 12,12)',
                                      "/97.5kg is a guess because the plate has lost its label. In fact, it's "
                                      'probably 100',
                                      '',
                                      '+ Bicycle cable crunch 37kg: 15',
                                      '(35kg:15)',
                                      '/Like a bicycle crunch but with a cable machine. Too easy',
                                      '/Hanging rotating knee raise?',
                                      '',
                                      'Cable crunch 42kg: 12',
                                      '(39kg: 15)',
                                      '/Close machines. Grip can be difficult',
                                      '/Close machine. Grip not difficult with 90 rowing degree handle',
                                      '/High RPE',
                                      '',
                                      '',
                                      'Machine lateral raise 64kg: 15,15',
                                      '(59kg: 15,20 / 64kg: 15,17)',
                                      "/Hole 4 because 3 doesn't have enough rom",
                                      '',
                                      '/+ Dumbbell lateral raise 9ea: 15,10',
                                      '/RPE 9',
                                      '',
                                      '',
                                      '/Seated face pull 25kg: 12,15',
                                      '(16)',
                                      '/Good weight previously',
                                      '',
                                      'Light face pull: 18',
                                      '/With improved form I feel better shoulder activation. Kept hands a little '
                                      'higher than usual too - good idea IMO',
                                      '/Keep it at 1 set',
                                      '',
                                      '/+ Machine rear delt fly 52kg: 12,12',
                                      '/RoM too short. Good weight if strict about RoM and hold behind the back',
                                      '',
                                      '/One arm face pulls 12kg: 12,12',
                                      '(15)',
                                      '/Hole 16. High feels better than low',
                                      '/Pause a moment',
                                      '',
                                      '/Athlean-X face pulls 50lb: 20',
                                      '(15)',
                                      '',
                                      'Machine curl 32kg: 12,10',
                                      '(12,10)',
                                      '/Good weight. Go for that full rom plus hold',
                                      '',
                                      '/Narrow grip EZ bar curl 10kg each side: 12, 12kg ea: 11',
                                      '/12kg each was too heavy',
                                      '',
                                      '/Og curl 14ea: 12',
                                      '/The wide hand seated curl',
                                      '',
                                      '/Hammer curl 14ea: 12',
                                      '',
                                      '/French press 26kg: 15,12',
                                      '/Not sure if I should be doing this exercise - shoulder reasons',
                                      '',
                                      '',
                                      'Tricep pushdown 36kg: 15, 41kg: 15',
                                      '(36kg: 15,15)',
                                      '/Usually wide stack machine for 36kg with rope for 2 sets',
                                      '/Previously challenging',
                                      '',
                                      '/+ Tricep overhead cable extension 32kg: 10',
                                      '',
                                      '',
                                      'Neck forwards curl, 15kg on forehead: 15,16',
                                      '(15kg: 15,16)',
                                      '/Increase weight, or shoot for 20 reps',
                                      '',
                                      '',
                                      '/Chest stretch',
                                      '',
                                      '',
                                      '/+ Ring practice',
                                      '/Incline hold in push-up position. Rings from top bar at max length. Hollow '
                                      'body posture with shoulders forwards (and down?) as recommended by the '
                                      'calisthenics guy',
                                      '/(Near) Straight arm dip hold',
                                      '/Do both exercises',
                                      '/Skipped because shoulders still recovering.',
                                      '',
                                      '/+ Back lever practise',
                                      '/On a bar (straight arms and hips. Active shoulders with depressed and '
                                      'retracted scapula)',
                                      '',
                                      'Dead hang',
                                      '',
                                      '',
                                      'Est 68 mins']
                                     ]
